name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-matrix:
    name: Build Plugin Components
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - pkg_name: ping-pong-plugin
            wasm_file: ping_pong_plugin
            component_name: ping_pong
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: taiki-e/install-action@wasm-tools
      - name: Build Plugin WASM Target
        run: cargo build --release --target wasm32-unknown-unknown -p ${{ matrix.pkg_name }}
      - name: Package WebAssembly Component
        run: |
          wasm-tools component new target/wasm32-unknown-unknown/release/${{ matrix.wasm_file }}.wasm -o ${{ matrix.component_name }}.component.wasm
